### ISSUE TITLE
About  the target reliability index with the related probabilistic model

### ISSUE THREAD

**Issue by Jungle-13** [rozsasarpi/Code-calibration-Belarus#8] opened 2022-03-23 02:49 UTC
Hello, Dear Sir. If the probabilistic model of the underlying variables is related to a 50-year reference period, the target reliability index β=3.8 corresponding to 50 years should be used (according to EN1990). However, in the paper, the snow load is the annual maxima, the Imposed load is the 5-year maxima, and the Basic wind velocity pressure is the annual max. So,in this case, should the 50-year target reliability index 3.8 be converted into a one-year one?  Thank you, sir

**Comment by rozsasarpi** [comment] 2022-03-23 07:26
Hi @Jungle-13, you are correct, the reference period of the time-dependent random variables should match the reference period of the target reliability. The paper reports one-year and five-year maxima distributions for convenience, when the calibration is done they are converted to the appropriate reference period, which is 50-year for the analyses reported in the paper.

* The reference period (`t_ref`) is specified here: https://github.com/rozsasarpi/Code-calibration-Belarus/blob/72a70f8eea4d09c149a64b6096f8ba22855d0d49/Matlab/main.m#L29
* The conversion from one and five years reference periods to `t_ref` happens here (assuming independent and identically distributed annual maxima):
https://github.com/rozsasarpi/Code-calibration-Belarus/blob/72a70f8eea4d09c149a64b6096f8ba22855d0d49/Matlab/prob_model.m#L88-L89
* The converted (scaled to matching reference period) time-dependent random variables are used in the reliability analyses.

The advantage of this implementation is that you can easily switch to a different reference period with respect to target reliabilities and time-dependent probabilistic models as well.

**Comment by Jungle-13** [comment] 2022-03-23 11:06
Ok,Sir.
That's **Wonderful**!
I think this issue can be closed.(**hawhaw)**
Thank you,Sir.

**Comment by Jungle-13** [comment] 2022-03-23 11:25
Sir,because after reading the comments about **k2m and bias of the variables**, I still don't quite understand **the difference** between the two, would you like to  tell me ? Thank you!

**Comment by rozsasarpi** [comment] 2022-03-23 11:49
I think the `bias` is some sort of residue of our earlier formulation of the connection between representative values and probabilistic models (probably it should have been removed from the code). I quickly checked the code and all bias values are 1.0, so they do not make a difference. I think the **`bias`es should be kept at 1.0 and can be ignored**.

`k2m` is the multiplier that connects the characteristic value of a random variable to its characteristic value: `mean = k2m*char`.
This is needed to establish the connection between the semi-probabilistic and "full"-probabilistic (reliability) analyses.

https://github.com/rozsasarpi/Code-calibration-Belarus/blob/72a70f8eea4d09c149a64b6096f8ba22855d0d49/Matlab/model_spec.m#L16

I hope this helps.

**Comment by Jungle-13** [comment] 2022-03-23 12:00
Yes, Sir. In your code, you also set **the mean of the variables to 1**, and I'd like to know why. Also, I don't see **the  k2m value of Resistance** from the code, so I want to ask you.

**Comment by rozsasarpi** [comment] 2022-03-23 12:30
### `k2m` for the resistance

That's a good point, it is likely because I was lazy in coding. I should have refactored it to make it more consistent and understandable.

You can see that there is also no `k2m` for the time-dependent component of the actions (`S`, `W`, `I`). This is because for these the connection between the characteristic and mean value is defined based on a fractile (see Table 3 of the paper). So we have two types of random variables, for one type the connection between the mean and characteristic value is defined through `k2m`, for others by using a fractile (see the details below). This reflects the messy state of standardization.

For the resistance it is the 2% non-exceedance probability:
https://github.com/rozsasarpi/Code-calibration-Belarus/blob/72a70f8eea4d09c149a64b6096f8ba22855d0d49/Matlab/pf_design.m#L45

For the above listed actions -- in the order how I listed them  -- their probability of non-exceedance `P_rep`:
https://github.com/rozsasarpi/Code-calibration-Belarus/blob/72a70f8eea4d09c149a64b6096f8ba22855d0d49/Matlab/main.m#L53

e.g. passed on to the snow time-dependent random variable:
https://github.com/rozsasarpi/Code-calibration-Belarus/blob/72a70f8eea4d09c149a64b6096f8ba22855d0d49/Matlab/model_spec.m#L204

Then these `P_rep` values are used to compute the characteristic values:
https://github.com/rozsasarpi/Code-calibration-Belarus/blob/72a70f8eea4d09c149a64b6096f8ba22855d0d49/Matlab/prob_model.m#L84

### Mean = 1

Due to how the problem is formulated, it should not matter what mean values you use, you should get the same outcomes in terms of calibrated partial factors. Using 1.0 is just a convenience. Try to change one or more mean values to something else than 1.0 and compare the obtained partial factors. (I hope that you will get the same outcomes as with means equal to 1. 😃)

**Comment by Jungle-13** [comment] 2022-03-23 13:03
Yeah,Sir.That is so clear.Thank you.

**Comment by rozsasarpi** [comment] 2022-03-23 13:08
I'm glad that it is clear. If your questions are answered please close the issue.

**Closed as completed** 2022-03-23 14:58 UTC
